artifacts_root: artifacts

data_ingestion:
  local_root_dir: artifacts/data_ingestion
  source_url: https://drive.google.com/file/d/1N-X8aij_9FtAtrDBfRHQKGE0vtIUC67i/view?usp=sharing
  local_data_file: artifacts/data_ingestion/clean_data.csv


data_validation:
  local_root_dir: artifacts/data_validation
  local_data_file: artifacts/data_ingestion/clean_data.csv
  STATUS_FILE: artifacts/data_validation/status.txt

data_transformation:
  local_root_dir : artifacts/data_transformation
  pickle_file : artifacts/data_transformation/transformer_v1.pkl
  local_data_file: artifacts/data_ingestion/clean_data.csv
  train_data: artifacts/data_transformation/train_data.csv
  test_data: artifacts/data_transformation/test_data.csv

model_trainer:
  local_root_dir: artifacts/model_trainer
  train_data: artifacts/data_transformation/train_data.csv
  model_pickle_file: artifacts/model_trainer/model_v1.pkl

model_evaluation:
  local_root_dir: artifacts/model_evaluation
  test_data_path: artifacts/data_transformation/test_data.csv
  model_path: artifacts/model_trainer/model_v1.pkl
  metric_file_name: artifacts/model_evaluation/metrics.json