artifacts_root: artifacts

data_ingestion:
  local_root_dir: artifacts/data_ingestion
  source_url: https://drive.google.com/file/d/1N-X8aij_9FtAtrDBfRHQKGE0vtIUC67i/view?usp=sharing
  local_data_file: artifacts/data_ingestion/clean_data.csv


data_validation:
  local_root_dir: artifacts/data_validation
  local_data_file: artifacts/data_ingestion/clean_data.csv
  STATUS_FILE: artifacts/data_validation/status.txt

